[package]
name = "calculator"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2024"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.23.1"

[dependencies]
lalrpop-util = { version = "0.23.1", features = ["lexer", "unicode"] }

[[bin]]
name = "calculator1"
path = "src/use_calculator1.rs" # <-- We added this line to specify the entry point of the program.

[[bin]]
name = "location"
path = "src/use_location.rs"

[[bin]]
name = "foobar"
path = "src/use_foobar.rs"

[[bin]]
name = "diamond"
path = "src/use_diamond.rs"

[[bin]]
name = "handling1"
path = "src/use_handling1.rs"

[[bin]]
name = "handling2"
path = "src/use_handling2.rs"

[[bin]]
name = "ast"
path = "src/use_buildingast.rs"