use std::str::FromStr;

grammar;

// This grammar has two nonterminals, Term and Num.
pub Term: f64 = { // pub:  LALRPOP will generate a public struct (named, TermParser) 
    <n:Num> => n, // that you can use to parse strings as Term. "n" refers to the value returned by the Num nonterminal.
    "(" <t:Term> ")" => t, // "t" is like "$2" in yacc/bison. It refers to the value returned by the Term nonterminal.
};

// Num is a private nonterminal.
Num: f64 = <s:r"\d+([.][0-9]+)?"> => f64::from_str(s).unwrap();