// See section "Type Inference" at the end of  https://lalrpop.github.io/lalrpop/tutorial/003_type_inference.html#type-inference
// ... However, <> may be confusing if you're dealing with complicated tuples. In that case, LALRPOP provides a pattern matching to unwrap the tuple.
grammar;

Foo = { A B };
Bar = { C Foo };

pub FooBar: String = {
    <(a, b):Foo> => format!("{a}{b}"), // format!("{a}{b}") returns "a".to_string() + "b".to_string()
    <(c, (a, b)):Bar> => format!("{c}{a}{b}")
};

A = { "a" };
B = { "b" };
C = { "c" };