// https://lalrpop.github.io/lalrpop/tutorial/004_full_expressions.html
use std::str::FromStr;

grammar;

pub Expr: i32 = {
    <l:Expr> "+" <r:Term> => l + r,
    <l:Expr> "-" <r:Term> => l - r,
    Term,
};

Term: i32 = {
    <l:Term> "*" <r:Factor> => l * r,
    <l:Term> "/" <r:Factor> => l / r,
    Factor,
};

Factor: i32 = {
    <n:Number> => n,
    "(" <e:Expr> ")" => e,
};

Number: i32 = {
    <n:r"[0-9]+"> => i32::from_str(n).unwrap(),
};
